### ISSUE TITLE
RatioLinearLayout

### ISSUE THREAD

**Issue by wilsonssss** [devsoulwolf/Android-RatioLayout#1]
why there are no RatioLinearLayout?

**Comment by vijayrawatsan** [comment]
Possibly because they already provide you a way to assign ratios.

**Comment by mzlogin** [comment]
You can find it in the source, probably @devsoulwolf forget to add it to README.
<https://github.com/devsoulwolf/Android-RatioLayout/blob/master/library/src/main/java/net/soulwolf/widget/ratiolayout/widget/RatioLinearLayout.java>

**Comment by vijayrawatsan** [comment]
@mzlogin @wilsonssss  Yep there does exists a RatioLinearLayout and it makes sense too. 
I confused the ratio of parent with weights of childs in parent.

**Comment by devsoulwolf** [comment]
@wilsonssss @mzlogin I'm very sorry! I forgot to add RatioLinearLayout to README, now has been added to the README, thank you for reminding me!

**Comment by devsoulwolf** [comment]
@vijayrawatsan I will implement the logic to extract as a Delegate, is what I need in order to facilitate everybody custom Layout or View, in fact, my initial purpose is to solve the ListView to the list of the picture show, picture in any resolution will not stretch, later found that it can also have more USES, thank you for your comments!
